# Курс "Программирование на языке Python. Уровень 4. Анализ и визуализация данных на языке Python. Библиотеки numpy, pandas, matplotlib"

## Модуль 2. Библиотека numpy

- Вспомним, что такое векторы, матрицы, тензоры, гиперплоскости и т.д. 



- Массивы (списки) в Python: индексы, срезы, итерация
- Векторы и матрицы в numpy, типы данных numpy
- Базовые операции в numpy: сложение, умножение, бродкаст
- Как нужно и как не нужно использовать numpy
- Линейная алгебра в numpy
- Векторизация, практика




## Массивы (списки) в Python: базовые операции, индексы, срезы, итерация

In [2]:
# активируем numpy
# если на этом этапе получаем сообщение об ошибке, выполняем pip install numpy / conda install numpy

import numpy as np


In [2]:
# создать список
list1 = ['a', 'b', 1, 0.5, {'James':'Brown', 'Luke':'Skywalker'}]
list2 = list(range(5))

#показать содержимое списка
print(list1)

#добавить элемент
list1.append('Something New') # ['a', 'b', 1, 0.5, {'Luke': 'Skywalker', 'James': 'Brown'}, 'Something New']
#убрать последний элемент (и вернуть его)
list2.pop() # [0, 1, 2, 3]
#сортировать (в порядке убывания)
list2.sort(reverse = True)  # [3, 2, 1, 0]


['a', 'b', 1, 0.5, {'James': 'Brown', 'Luke': 'Skywalker'}]


In [3]:
# обращение к элементам списка
nums = list(range(5))     
print(nums)               # выведет на экран "[0, 1, 2, 3, 4]"
print(nums[2])            # выведет на экран 2-й элемент: "2"
print(nums[-3])           # выведет на экран 3-й элемент с конца: "2"
print(nums[2:4])          # выведет на экран срез со 2-го до 4-го: "[2, 3]"
print(nums[2:])           # выведет на экран срез со 2-го и до конца: "[2, 3, 4]"
print(nums[:2])           # выведет на экран срез с начала и до 2-го элемента "[0, 1]"
print(nums[:])            # срез всего списка: "[0, 1, 2, 3, 4]"
print(nums[:-2])          # отрицательный срез, все элементы, кроме двух в конце: "[0, 1, 2]"
print(nums[::2])          # все четные элементы
print(nums[1::2])         # все нечетные элементы
nums[2:4] = [8, 9]        # заместит элементы со 2-го до 4-го списком [8, 9]
print(nums)               # выведет на экран "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
2
2
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 2, 4]
[1, 3]
[0, 1, 8, 9, 4]


## Векторы и матрицы в numpy

### Различные способы создания векторов и матриц

In [4]:
a = np.array([1, 2, 3])   # Создаем вектор как массив numpy, из списка
print(type(a))            # выведет на экран "<class 'numpy.ndarray'>"
print(a.shape)            # выведет на экран "(3,)"
print(a[0], a[1], a[2])   # выведет на экран "1 2 3"
a[0] = 5                  # Запишем что-нибудь в первый элемент
print(a)                  # выведет на экран "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Создаем матрицу размера 2х3 из двух списков
print(b.shape)                     # выведет на экран "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # выведет на экран "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [5]:
# некоторые встроенные функции для создания специфических матриц
nat_nums = np.arange(10) # вектор из натуральных чисел
all_zeros_2x2 = np.zeros((2,2))   # Создаем нулевую матрицу размером 2x2
all_ones_1x2 = np.ones((1,2))    # Единичная матрица размера 1x2
all_sevens_2x2 = np.full((2,2), 7)  # Матрица 2х2, заполненная числом 7
identity_matrix = np.eye(2)         # Матрица идентичности 2x2 (все эелементы - 0, главная диагональ - 1)

print(nat_nums)
print(all_zeros_2x2)
print(all_ones_1x2)
print(all_sevens_2x2)
print(identity_matrix)
print(random_matrix)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


NameError: name 'random_matrix' is not defined

### Случайные числа

Используем подмодуль ```np.random```, его специально устанавливать не нужно.

In [6]:
random_matrix = np.random.random((2,2))  # Матрица 2x2 со случайно заданными вещ. числами от 0 до 1
print(random_matrix)
randint_matrix_3x3 = np.random.randint(0,10, (3,3)) # Матрица 3х3 со случайнами целыми числами
print(randint_matrix_3x3)

vec = np.arange(42) * 10
print(vec)
choice = np.random.choice(vec, 3) # выберет случаные 3 элемента из массива
print(choice)

print(np.random.choice(random_matrix, 2)) # работает только с векторами

[[0.02804617 0.24606847]
 [0.67747742 0.7785153 ]]
[[2 1 6]
 [6 4 2]
 [1 6 8]]
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360 370 380 390 400 410]
[ 10 170 210]


ValueError: a must be 1-dimensional

#### Практика

Выполните следующие упражнения:



In [12]:
# создайте вектор, состоящий из натуральных чисел от 1 до 7
v_nat_1_7 = np.arange(1,8)
print(v_nat_1_7)


# создайте матрицу размером 2x3 из списка списков
m_2x3 = np.array([[1,2,3],[4,5,6]])

# создайте вектор, состоящий из квадратов натуральных чисел, начиная с 1 до 10
v_sqrs = np.arange(1,10)**2
print(v_sqrs)



[1 2 3 4 5 6 7]
[ 1  4  9 16 25 36 49 64 81]


### Обращение к элементам матриц, срезы

In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Эти выражения эквивалентны
print(a[0][2])
print(a[0, 2]) # лучше использовать это, т.к. оно выполняется оптимальнее

# Срежем: возьмем ряды с 0-го до 2-го и колонки с 1-й до 3-ей
b = a[:2, 1:3]
# [[2 3]
#  [6 7]]

## ВНИМАНИЕ: нулевое измерение - всегда "по вертикали", первое - по "горизонтали"!

# Срез массива numpy - это представление оригинального массива
# Попытка изменить там данные приведет к изменению оригинального массива
print(a[0, 1])   # Выведет "2"
b[0, 0] = 77     # b[0, 0] - то же самое, что и a[0, 1]
print(a[0, 1])   # выведет на экран "77"

# Срезы матриц можно получать как в виде векторов, так и 2-мерных матриц с размерностью 1xn или nx1
print(a[1, :]) ## выведет на экран "[5 6 7 8]"
print(a[1:2, :]) ## выведет на экран "[[5 6 7 8]]" 
print(a[:, 1]) ## выведет на экран "[77  6 10]"
print(a[:, 1:2]) ## ВОПРОС: что эта команда выведет на экран?

3
3
2
77
[5 6 7 8]
[[5 6 7 8]]
[77  6 10]
[[77]
 [ 6]
 [10]]


#### Практические задачи

Выполните следующие упражнения:

In [30]:
print(a)

# для матрицы a - сделайте срез в виде квадратных матриц 2x2 из левого верхнего левого и правого нижнего углов
a_upper_left_2x2 = a[0:2, 0:2]

print(a_upper_left_2x2)

a_lower_right_2x2 = a[-2:, -2:]
print(a_lower_right_2x2)

# для той же матрицы получите в виде векторов
# 2-й с конца столбец
a_col_2 = a[:, -2]
print(a_col_2)

# последнюю строку
a_last_row = a[-1, :]
print(a_last_row)


[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1 77]
 [ 5  6]]
[[ 7  8]
 [11 12]]
[ 3  7 11]
[ 9 10 11 12]


### Индексирование: булев индекс и индекс массивом целых чисел

Для доступа к элементам массивов numpy можно использовать "маску" - матрицу булевых элементов, а также список целых чисел.

In [31]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Эта команда возвращает массив numpy из булевых элементов
                     # той же размерности, что и a. Его элементы True, если
                     # соотв. элементы a > 2 

print(bool_idx)      # выведет на экран "[[False False]
                     #                   [ True  True]
                     #                   [ True  True]]"

# Используя эту матрицу, мы можем получить вектор из элементов матрицы a, которые соответсвуют условию
print(a[bool_idx])  # выведет на экран "[3 4 5 6]"

# ...и все это - одной строкой:
print(a[a > 2])     # выведет на экран "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Для булевых масок определены следующие логические операции:
- ```&``` - логическое "и"
- ```|``` - логическое "или"
- ```~``` - логическое отрицание.

**Обратите внимание:** каждый операнд в логическом выражении порождает свою булеву маску, далее эти операторы работают как битовые, выполняя логические операции для каждого элемента масок-операндов.

In [32]:
a = np.array([[1,2], [3, 4], [5, 6]])
bm_1 = (a>2)
bm_2 = (a<5)
print( bm_1)
print( bm_2 )
print( bm_1 & bm_2 ) # "&" работает как "and" для каждого элемента маски-операнда
print(a[ bm_1 & bm_2 ])

print( a[ (a<2) & (a>5) ] ) # не забывайте про скобки для каждой анонимной булевой маски!

[[False False]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [False False]]
[[False False]
 [ True  True]
 [False False]]
[3 4]
[]


"Fancy indexing" - индексирование массивом целых чисел.

In [33]:
a = np.arange(0, 100, 10)
print(a) # [ 0 10 20 30 40 50 60 70 80 90]

b = a[[2, 3, 2, 4, 2]] 
print(b) # [20 30 20 40 20]

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20]


#### Практика

Выполните следующие упражнения:

1. Из среза в виде квадратной матрицы 3x3, взятой с правого конца, выберите следующие элементы:

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a_3x3_last = a[-3:,-3:]
print(a_3x3_last)

# 1. те, которые меньше 10
print(a_3x3_last[a_3x3_last<10])

# 2. нечетные элементы
print(a_3x3_last[a_3x3_last%2!=0])


[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[2 3 4 6 7 8]
[ 3  7 11]



2. Создайте массив из 10 натуральных чисел и присвойте 3-м случайным элементам из этого массива число 5000.

In [67]:
a = np.arange(0, 1000, 100)
print(a)
choise  = np.random.choice(np.arange(a.shape[0]), 3, replace=False)
a[ choise ] = 5000
print(a)
print(np.arange(a.shape[0]))


[  0 100 200 300 400 500 600 700 800 900]
[5000  100 5000  300  400  500  600 5000  800  900]
[0 1 2 3 4 5 6 7 8 9]


### Изменение форм и размерностей массивов numpy

Изменить форму массива можно функцией ```reshape( dim )```, где dim - кортеж с новой размерностью массива. Будет возвращена копия объекта, но область данных останется неизменной, а изменения в оригинальном массиве будут отражены в порожденной копии. При этом, если одна из размерностей массива неизвестна, на ее месте можно указать ```-1```.

Кортеж с текущей размерностью массива находится в его свойстве ```shape```.

"Плоское" представление массива вернет метод ```ravel()```, а метод ```flatten()``` вернет его копию.

In [68]:
a = np.arange(9) # [0 1 2 3 4 5 6 7 8]
print(a)
b = a.reshape((3,3)) 
# [[  0   1   2]
#  [  3   4   5]
#  [  6   7   8]]
a[5] = 100
print(b)
# [[  0   1   2]
#  [  3   4 100]
#  [  6   7   8]]

r = b.ravel()
f = b.flatten()
print(f)
f[4] = 200
print(a) # [  0   1   2   3   4 100   6   7   8]
r[4] = 200
print(a) # [  0   1   2   3 200 100   6   7   8]

[0 1 2 3 4 5 6 7 8]
[[  0   1   2]
 [  3   4 100]
 [  6   7   8]]
[  0   1   2   3   4 100   6   7   8]
[  0   1   2   3   4 100   6   7   8]
[  0   1   2   3 200 100   6   7   8]


#### Практика

Создайте матрицу случайной размерности от 2 до 16, заполненную нулями и на ее базе создайте новую матрицу, обратной размерности, заполненную случайными числами.

In [87]:
dims = ( (14 * np.random.random(2) // 1) + 2).astype(dtype=np.int64)
dims
#c = np.random.random(dims.shape).reshape
c=np.zeros(dims)
d=np.random.random((dims[::-1]))
print(dims)
print(dims[::-1])
d

[7 8]
[8 7]


array([[0.17728601, 0.15027555, 0.9287091 , 0.87219443, 0.82985732,
        0.50385251, 0.4110734 ],
       [0.75049488, 0.42772064, 0.78433109, 0.89862753, 0.35892371,
        0.41207053, 0.45614601],
       [0.41470577, 0.93951914, 0.89447782, 0.94743154, 0.51021626,
        0.43014412, 0.64400177],
       [0.20407976, 0.63244322, 0.0990062 , 0.3569914 , 0.61736378,
        0.95423382, 0.11424144],
       [0.71617326, 0.74704268, 0.11587901, 0.15191047, 0.90806655,
        0.26940002, 0.17866961],
       [0.65100894, 0.96316965, 0.08434432, 0.54522768, 0.07162076,
        0.58651012, 0.99422444],
       [0.96372961, 0.7143975 , 0.25720118, 0.65529312, 0.87417284,
        0.74653594, 0.24514782],
       [0.89081374, 0.32613596, 0.6814352 , 0.25375616, 0.850628  ,
        0.05072863, 0.28044333]])


### Конкатенация  и разбиение массивов

Используются функции ```concatenate()``` и ```split()```.


In [88]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
concats_0 = np.concatenate([arr1, arr2], axis= 0) # вертикальная конкатенация, есть эквивалент vstack()
print(concats_0)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
concats_1 = np.concatenate([arr1, arr2], axis= 1) # горизонтальная конкатенация, есть эксивалент hstack()
print(concats_1)

first, second, third = np.split(concats_0, [1,2], axis=0) # вертикальное разбиение
print(first)
print(second)
print(third)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[1 2 3]]
[[4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [90]:
x = concats_0[:, :-1]
x
y = concats_0[:, -1:]
y

array([[ 3],
       [ 6],
       [ 9],
       [12]])

### Типы данных numpy

In [96]:
x = np.array([1, 2])   # numpy сам подберет тип данных
print(x.dtype)         # выведет на экран "int64"

x = np.array([1.0, 2.0])   # Здесь numpy выберет float64
print(x.dtype)             # выведет на экран "float64"

x = np.array([1, 2], dtype=np.float64)   # Тут мы заставим numpy сконвертировать данные во float
print(x.dtype)                         # выведет на экран "float64"

# конвертация типов производится методом astype(), он возвращает копию текущего массива
y = x.astype(dtype=np.int32) 

x = np.array([1, 2, 2.5, 'john'])   # Из-за такого тут будет сообщение об ошибке

print(x.dtype)
print(x)
np.nan
x


int64
float64
float64
<U32
['1' '2' '2.5' 'john']


array(['1', '2', '2.5', 'john'], dtype='<U32')

### Операции с массивами numpy

#### Поэлементные операции

Выполняются для каждого элемента массива или среза.

In [97]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Поэлементное сложение:
print(np.add(x, y)) # можно использовать функцию add()
print(x + y) # можно просто использовать оператор "+"
# То же самое с другими арифметическими операциями: вычитанием, умножением и делением

# Взятие квадратного корня
print(np.sqrt(x))

# Взятие экспоненты
print(np.exp(x))

# Логарифмирование
print(np.log(x))

# Другие операции над элементами массивов numpy - см. документацию

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[0.         0.69314718]
 [1.09861229 1.38629436]]


#### Практика

Выполните следующие упражнения:

In [104]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# получите срез в виде квадратной матрицы 3x2, с левого конца
a_3x2_left = a[:,:2]

# 1. из него получите матрицу, содержащую эти элементы, возведенные в квадрат
a_3x2_left2 = a_3x2_left **2
a_3x2_left2

# 2. возьмите срез 3x2 с правого конца и сложите со имеющимся срезом
a_3x2_right = a[:, -2:]
x = a_3x2_left + a_3x2_right
x

array([[ 4,  6],
       [12, 14],
       [20, 22]])

### Операции из области линейной алгебры

Умножение матриц, скалярное произведение векторов (как частный случай умножения матриц), транспонирование - базовые функции пакета numpy.

В модуле numpy.linalg еще есть встроенные функции для расчетов рангов матриц, определителей, вычисления собственных чисел, а также для решения линейных уравнений:
 - ```np.linalg.solve(A, b)``` - вычисляет единственное решение системы линейных уравнений, где A - квадратная матрица коэффициентов, b - вектор значений
 - ```np.linalg.matrix_rank(A)``` - вычисляет ранг матрицы
 - ```np.linalg.inv(A)``` - вычисляет обратную матрицу
 - ```np.linalg.eig(A)``` - вычисляет собственный вектор или собственное число матрицы

In [107]:
# создаем две матрицы
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# и два вектора
v = np.array([9,10])
w = np.array([11, 12])

# Скалярное произведение векторов; оба выражения дают 219
print(v.dot(w))
print(np.dot(v, w))

print('-'*10)

# Умножение матрицы на вектор, оба выражения возвращают вектор [29 67]
print(x.dot(v))
print(np.dot(x, v))

print('-'*10)

# Умножение матриц, в итоге получаем
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
----------
[29 67]
[29 67]
----------
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Бродкастинг (broadcasting)

В русскоязычной литературе этот термин также встречается как "укладывание".

In [108]:
# Добавим вектор v к каждой строке матрицы x
# результат запишем в матрицу y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # результат "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
            
            
### как это было бы без бродкастинга
y = np.empty_like(x)   # создаем пустой массив "как x"

# В ЦИКЛЕ добываем векторы из x, складываем с v и записываем в y
for i in range(4):
    y[i, :] = x[i, :] + v

# ИЛИ
vv = np.tile(v, (4, 1))   # размножаем вектор v в матрицу той же размерности, что x
y = x + vv  # скалыдваем
# уже лучше, но все равно не то

# Бродкастинг также работает и со скалярными данными
y = (x * 2)
print(y)
# [[ 2  4  6]
#  [ 8 10 12]
#  [14 16 18]
#  [20 22 24]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [112]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v=np.array([1, 0, 0, 1])
v.reshape((1, v.shape[0], 1)) + x

array([[[ 2,  3,  4],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13]]])

### Агрегатные вычисления

In [113]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(x.sum()) # сумма

print(x.mean()) # среднее

print(x[2].sum()) # сумма по 2-й строке

print(np.sum(x[:, 1])) # сумма по 1-му столбцу



78
6.5
24
26


Функции ```max()``` и ```argmax()```:

In [114]:
a_vec = (np.random.random( 10 ) * 100).astype(dtype=np.int64)
print(a_vec)
print(a_vec.max()) # возвращает максимум
print(a_vec.argmax()) # возвращает позицию для элемента с максимальным значением

[14 86 37 92 72 49 61  9 56  3]
92
3


In [117]:
m = np.random.randint(0,10, (3,3)  )
print(m, m.ravel())
m.argmax() # вернет индекс как будто матрица "раскатана" в вектор

[[7 0 2]
 [7 6 1]
 [8 3 0]] [7 0 2 7 6 1 8 3 0]


6

#### Сортировка

In [130]:
a_vec = (np.random.random( 10 ) * 100).astype(dtype=np.int64)
print(a_vec)
print(a_vec.sort())
print(np.sort(a_vec))
%time print(a_vec[np.argsort(-a_vec)])
print(a_vec)
#print(a_vec.argsort(reverse=True))
print(a_vec[ a_vec.argsort()[:5] ])

[89 98 57  2 76 50 70  8 29 68]
None
[ 2  8 29 50 57 68 70 76 89 98]
[98 89 76 70 68 57 50 29  8  2]
CPU times: user 193 µs, sys: 29 µs, total: 222 µs
Wall time: 181 µs
[ 2  8 29 50 57 68 70 76 89 98]
[ 2  8 29 50 57]


In [127]:
%time np.sort(a_vec)[::-1]

CPU times: user 29 µs, sys: 5 µs, total: 34 µs
Wall time: 37.2 µs


array([64, 61, 58, 27, 25, 23, 20, 17, 15,  7])

### Как надо и как не надо пользоваться numpy

Использование numpy неэффективно, если объекты numpy обрабатывать вне самого numpy. Подходите к данным как к векторам и матрицам, обрабатывайте их эффективно!

In [128]:
# На примере задачи "получить сумму  квадратов натуральных чисел от 0 до 1000"
# чистый python:
%timeit -n200 x = sum(x*x for x in range(100))

# наивный numpy - хуже чистого Python'а
na = np.arange(1000)
%timeit -n200 x = sum(na*na)

# векторизованный numpy
%timeit -n200 x = np.dot(na, na)

7.33 µs ± 797 ns per loop (mean ± std. dev. of 7 runs, 200 loops each)
99.2 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 200 loops each)
3.68 µs ± 958 ns per loop (mean ± std. dev. of 7 runs, 200 loops each)


## Практические задания

Решите следующие простые задания, не прибегая к использованию циклов и исключая использование функций python, таких как ```sum()```, ```max()```, и т.д:

In [162]:
# создайте массив numpy из 10-ти случайных натуральных чисел
a = np.random.randint(0, 10, (10))
min_a = a.min()
min_idx = a.argmin()

print(a)
print(min_a)
print(min_idx)

a[ a == min_a] = -100
print(a)


b = a[::-1]
print(b)

c = a + b
print(c)

print(c.sum())

print(np.sum(c**2))
print((c**2).sum())
# найдите минимум в этом массиве и индекс этого минимального значения, замените этот элемент на -100


# сложите этот массив с его "зеркальным отображением"
# Палиндром

# посчитайте сумму элементов получившегося массива

# посчитайте сумму квадратов элементов получившегося массива

[2 6 3 1 2 1 9 7 3 4]
1
3
[   2    6    3 -100    2 -100    9    7    3    4]
[   4    3    7    9 -100    2 -100    3    6    2]
[  6   9  10 -91 -98 -98 -91  10   9   6]
-328
36204
36204


1 . Решите систему уравнений методом solve:

$\begin{cases}
x_1 - x_2 + x_3 = 3 \\
2x_1 + x_2 + x_3 = 11 \\
x_1 + x_2 + 2x_3 = 8
\end{cases}
$

In [5]:
A = np.array([[1, -1, 1], [2, 1, 1], [1, 1, 2]])
B = np.array([3, 11, 8])
np.linalg.solve(A, B)


array([4., 2., 1.])

2 . Решите систему уравнений методом обратной матрицы: $A * x = b$, $x = A^-1 * b$

$\begin{cases}
2x_1 + x_2 - 2x_3 = -3 \\
x_1 - 2x_2 + x_3 = 11 \\
3x_1 + x_2 - x_3 = 0
\end{cases}
$


In [9]:
a = [[2, 1, -2], [1, -2, 1], [3, 1, -1]]
b = [-3, 11, 0]
np.linalg.inv(a).dot(b)

array([ 1.75, -4.  ,  1.25])

3 . Найдите расстояние от точки $M(1;0;-2)$  
до плоскости, заданной уравнением $2x-y+2z=4$.

Формула для рассчета расстояния от точки до плоскости:  
$d_{01}=\frac{\left|\left(\bar r_0\cdot \bar n_1\right)+D_1\right|}{\left|\bar n_1\right|}$, где $r_0$ - радиус-вектор к точке,  $n_1$ - вектор нормали к плоскости, $D_1$ - константа из уравнения плоскости.

In [12]:
M = np.array([1, 0, -2])
n = np.array([2, -1, 2])
D = 4
d = np.abs(M.dot(n) + D) / np.sqrt(n.dot(n))
d

0.6666666666666666

#### Задачи на векторизацию, булевы маски и бродкастинг

Требуется решить их с использованием объектов и функций библиотеки ```numpy```, без использования циклов, с минимальным количеством строк кода. 

1. Найти сумму ряда чисел от 0 до 100.

In [15]:
np.arange(100).sum()

4950

2. Выведите списки чисел, из данного массива:\
    2.1 кратные 3-м \
    2.2 кратные 5-ти \
    2.3 кратные одновременно и 3-м, и 5-ти \
    2.4 кратные как 3-м, так и 5-ти, кроме четных чисел

In [25]:
n = np.arange(100)
m_3 = (n % 3 == 0)
b = n[m_3]
b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
m_5 = (n % 5 == 0)
b = n[m_5]
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [33]:
m_3 = (n % 3 == 0)
m_5 = (a % 5 == 0)
print(n[m_3 & m_5])

[ 0 15 30 45 60 75 90]


In [37]:
m_2 = (n % 2 == 0)
print(n[m_3 & m_5 & ~m_2])

[15 45 75]


3. У вас есть матрица, столбцы которой содержат данные о диаметре и длине стальных циллиндрических прутков, которые подлежат покраске. Посчитайте расход краски в кг, если известно, что толщина покрытия - 0.001 мм, а плотность краски $5000 кг/м^3$.

In [51]:
M = np.array([[1, 2, 3 , 2, 1], [0.02, 0.02, 0.025, 0.025, 0.015]]).T
print(M)
D = M[:, 1]
L = M[:, 0]
S = (np.pi*D*L + 2*np.pi*(D/2)**2).sum()
print(S)

S = (np.pi * D.dot(L) + 0.5 * np.pi * D.dot(D)).sum()
print(S)
#V = S * h
#W = V * ro

[[1.    0.02 ]
 [2.    0.02 ]
 [3.    0.025]
 [2.    0.025]
 [1.    0.015]]
0.631892092361417
0.631892092361417


4. Создайте матрицу размера MxN и заполните ее случайными числами в диапазоне от 0 до 1. \
    4.1 К каждой строке матрицы прибавьте ряд натуральных чисел от 0 до N. \
    4.2 К каждому столбцу матрицы прибавьте ряд десятков натуральных чисел от M*10 до 0 (например, 40, 30, 20, 10 etc).

In [71]:
M = 5
N = 4
A = np.random.random((M, N))
L = np.arange(1, N + 1)
print(A + L)
T = np.arange(M * 10, 0, -10)
print(T)
K = T.reshape((M, 1))
K + A + L

[[1.7335275  2.59835836 3.10881334 4.8563137 ]
 [1.57394676 2.23367032 3.17213619 4.88717692]
 [1.39159994 2.47808181 3.29787458 4.60483697]
 [1.73760143 2.10200239 3.20719131 4.89402217]
 [1.65678644 2.22964584 3.99578776 4.635177  ]]
[50 40 30 20 10]


array([[51.7335275 , 52.59835836, 53.10881334, 54.8563137 ],
       [41.57394676, 42.23367032, 43.17213619, 44.88717692],
       [31.39159994, 32.47808181, 33.29787458, 34.60483697],
       [21.73760143, 22.10200239, 23.20719131, 24.89402217],
       [11.65678644, 12.22964584, 13.99578776, 14.635177  ]])